CREATE TABLE selected_shipments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    volume INTEGER NOT NULL,
    revenue DECIMAL(19,2) NOT NULL,
    optimization_request_id VARCHAR(36) NOT NULL,
    FOREIGN KEY (optimization_request_id) REFERENCES optimization_requests(id)
);
